import type { Metadata } from 'next';
import './globals.css';
import QueryProvider from '@/providers/query-provider';
import localFont from 'next/font/local';
import Appbar from '@/shared/ui/header/AppBar';

const pretendard = localFont({
  src: '../../static/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable} font-pretendard antialiased`}>
        <QueryProvider>
          <Appbar />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
