import axiosInstance, {
  axiosDeleteComment,
  axiosEditComment,
  axiosGetComments,
  axiosWriteComment,
} from './axios/axios';
import {
  axiosGoogleAccessToken,
  axiosKakaoAccessToken,
  axiosNaverAccessToken,
  axiosConnectSSE,
  axiosDeleteUser,
  axiosDisconnectSSE,
  axiosEditUsername,
  axiosHotBoardList,
  axiosLike,
  axiosMyPosts,
  axiosMyScraps,
  axiosPost,
  axiosPosts,
  axiosRealtimeTop10,
  axiosScrapPost,
  axiosTimeSync,
  axiosUploadImages,
  axiosUploadPost,
  axiosUserProfile,
  axiosHotBoardInfo,
  axiosGetAutocomplete,
  axiosUpdatePost,
  axiosSearchRealtimeBoards,
  axiosSearchRealtimePosts,
  axiosDeletePost,
} from './axios/axios';

import { SSE } from './sse/sse';

export {
  axiosInstance,
  axiosGoogleAccessToken,
  axiosKakaoAccessToken,
  axiosNaverAccessToken,
  axiosConnectSSE,
  axiosDeleteUser,
  axiosDisconnectSSE,
  axiosEditUsername,
  axiosHotBoardList,
  axiosLike,
  axiosMyPosts,
  axiosMyScraps,
  axiosPost,
  axiosPosts,
  axiosRealtimeTop10,
  axiosScrapPost,
  axiosTimeSync,
  axiosUploadImages,
  axiosUploadPost,
  axiosUserProfile,
  axiosHotBoardInfo,
  axiosGetAutocomplete,
  axiosGetComments,
  axiosWriteComment,
  axiosDeleteComment,
  axiosEditComment,
  axiosUpdatePost,
  axiosSearchRealtimeBoards,
  axiosSearchRealtimePosts,
  axiosDeletePost,
  SSE,
};
